version: '3.8'

services:
  react-app:
    build:
      context: ./my-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - fastapi-app

  fastapi-app:
    build:
      context: ./my-fastapi-app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
